# Generated by Django 5.0.14 on 2026-07-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grade_change', '0001_initial'),
        ('prediction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='The telemetry time this recommendation targets.')),
                ('recommended_machine_speed', models.FloatField(help_text='Recommended setpoint for Machine Speed (meters/min).')),
                ('recommended_headbox_flow', models.FloatField(help_text='Recommended setpoint for Headbox Flow (liters/min).')),
                ('recommended_steam_pressure', models.FloatField(help_text='Recommended setpoint for Steam Pressure (bar).')),
                ('recommended_consistency', models.FloatField(help_text='Recommended setpoint for Stock Consistency (%).')),
                ('expected_improvement', models.FloatField(help_text='Expected percentage improvement in stabilization time / waste reduction (%).')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified')], default='PENDING', help_text='Operator feedback status on this recommendation.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the recommendation was created.')),
                ('grade_change', models.ForeignKey(help_text='The grade change run this recommendation targets.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='grade_change.gradechange')),
                ('prediction', models.ForeignKey(help_text='The prediction this recommendation is based on.', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='prediction.prediction')),
            ],
            options={
                'verbose_name': 'Recommendation',
                'verbose_name_plural': 'Recommendations',
                'ordering': ['-created_at'],
            },
        ),
    ]
