from django.db import models
from django.utils.translation import gettext_lazy as _
from grade_change.models import GradeChange
from prediction.models import Prediction


class Recommendation(models.Model):
    """
    Stores optimal setpoint recommendations generated by the recommendation engine.
    """
    class Statuses(models.TextChoices):
        PENDING = 'PENDING', _('Pending')
        ACCEPTED = 'ACCEPTED', _('Accepted')
        REJECTED = 'REJECTED', _('Rejected')
        MODIFIED = 'MODIFIED', _('Modified')

    prediction = models.ForeignKey(
        Prediction,
        on_delete=models.CASCADE,
        related_name='recommendations',
        help_text=_("The prediction this recommendation is based on.")
    )
    grade_change = models.ForeignKey(
        GradeChange,
        on_delete=models.CASCADE,
        related_name='recommendations',
        help_text=_("The grade change run this recommendation targets.")
    )
    timestamp = models.DateTimeField(
        help_text=_("The telemetry time this recommendation targets.")
    )
    recommended_machine_speed = models.FloatField(
        help_text=_("Recommended setpoint for Machine Speed (meters/min).")
    )
    recommended_headbox_flow = models.FloatField(
        help_text=_("Recommended setpoint for Headbox Flow (liters/min).")
    )
    recommended_steam_pressure = models.FloatField(
        help_text=_("Recommended setpoint for Steam Pressure (bar).")
    )
    recommended_consistency = models.FloatField(
        help_text=_("Recommended setpoint for Stock Consistency (%).")
    )
    expected_improvement = models.FloatField(
        help_text=_("Expected percentage improvement in stabilization time / waste reduction (%).")
    )
    status = models.CharField(
        max_length=20,
        choices=Statuses.choices,
        default=Statuses.PENDING,
        help_text=_("Operator feedback status on this recommendation.")
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text=_("When the recommendation was created.")
    )

    class Meta:
        ordering = ['-created_at']
        verbose_name = _('Recommendation')
        verbose_name_plural = _('Recommendations')

    def __str__(self) -> str:
        return f"Rec for GC {self.grade_change_id} (Status: {self.status}, Expected Improvement: {self.expected_improvement}%)"
