# Generated by Django 5.0.14 on 2026-07-15 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeChange',
            fields=[
                ('grade_change_id', models.CharField(help_text='Unique identifier for the grade change run (e.g. from CSV or historian).', max_length=100, primary_key=True, serialize=False)),
                ('target_grade', models.CharField(help_text='The goal grade type being transitioned to.', max_length=100)),
                ('start_time', models.DateTimeField(help_text='Timestamp when the grade change initiated.')),
                ('end_time', models.DateTimeField(blank=True, help_text='Timestamp when the grade change process finished or stabilized.', null=True)),
                ('status', models.CharField(choices=[('STABILIZING', 'Stabilizing'), ('STABILIZED', 'Stabilized'), ('FAILED', 'Failed')], default='STABILIZING', help_text='Current operational status of this grade change.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(blank=True, help_text='The operator presiding over this grade change.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grade Change',
                'verbose_name_plural': 'Grade Changes',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(help_text='Date and time of the sensor telemetry reading.')),
                ('machine_speed', models.FloatField(help_text='Speed of the paper machine (meters/min).')),
                ('headbox_flow', models.FloatField(help_text='Flow rate of pulp stock in headbox (liters/min).')),
                ('consistency', models.FloatField(help_text='Fiber consistency percentage in stock (%).')),
                ('steam_pressure', models.FloatField(help_text='Steam drying cylinder pressure (bar).')),
                ('basis_weight', models.FloatField(help_text='Measured basis weight of paper (g/m²).')),
                ('moisture', models.FloatField(help_text='Moisture percentage in the paper sheet (%).')),
                ('grade', models.CharField(help_text='Current paper grade reported by DCS.', max_length=100)),
                ('grade_change', models.ForeignKey(help_text='The grade change run this sensor telemetry belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='grade_change.gradechange')),
            ],
            options={
                'verbose_name': 'Sensor Telemetry',
                'verbose_name_plural': 'Sensor Telemetries',
                'ordering': ['timestamp'],
                'indexes': [models.Index(fields=['grade_change', 'timestamp'], name='grade_chang_grade_c_c5182a_idx')],
            },
        ),
    ]
