# Generated by Django 5.0.14 on 2026-07-15 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('MODIFIED', 'Modified')], help_text="Operator's final decision on this recommendation.", max_length=20)),
                ('modified_machine_speed', models.FloatField(blank=True, help_text='Operator overridden setpoint for Machine Speed (if modified).', null=True)),
                ('modified_headbox_flow', models.FloatField(blank=True, help_text='Operator overridden setpoint for Headbox Flow (if modified).', null=True)),
                ('modified_steam_pressure', models.FloatField(blank=True, help_text='Operator overridden setpoint for Steam Pressure (if modified).', null=True)),
                ('modified_consistency', models.FloatField(blank=True, help_text='Operator overridden setpoint for Stock Consistency (if modified).', null=True)),
                ('comments', models.TextField(blank=True, help_text='Operator comments or notes regarding their choice.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this feedback was submitted.')),
                ('operator', models.ForeignKey(help_text='The operator who submitted this feedback.', on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operator Feedback',
                'verbose_name_plural': 'Operator Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
