# Generated by Django 5.0.14 on 2026-07-15 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('feedback', '0001_initial'),
        ('recommendation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='recommendation',
            field=models.OneToOneField(help_text='The recommendation this feedback is for.', on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='recommendation.recommendation'),
        ),
    ]
